"use client";

import Link from "next/link";
import { ArrowUpRight, BarChart3, Bot, Check, Code2, Component, Database, FileSearch, Gauge, Globe, HelpCircle, Layers3, Layout, MonitorSmartphone, MousePointerClick, Palette, PenTool, RefreshCw, Rocket, Search, ShieldCheck, ShoppingCart, Smartphone, Sparkles, TrendingUp, Zap, type LucideIcon } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import type { ServiceData } from "@/lib/service-data";

const icons: Record<string, LucideIcon> = { PenTool, Code2, Search, Bot, Sparkles, Layers3, Palette, MousePointerClick, MonitorSmartphone, Layout, Component, Rocket, Gauge, ShieldCheck, Database, Smartphone, ShoppingCart, FileSearch, Zap, Globe, BarChart3, RefreshCw, TrendingUp };
const intros: Record<string, string> = {
  "product-design-ux": "We design the structure before the visuals. You'll get clear user flows, intuitive layouts, and a design system that your developers can actually work with.",
  "web-development": "We build with Next.js, React, and TypeScript. You'll get production-ready code, clear documentation, and a site that your team can maintain.",
  "website-redesign": "Migrate your existing site to Next.js and React. We'll update the design, improve performance, and preserve your SEO rankings and content.",
  "ai-integration": "Integrate AI into your existing application. Custom chatbots, document search, and workflow automation using OpenAI, Anthropic, or open-source models.",
};

export function ServicePageContent({ service }: { service: ServiceData }) {
  const icon = icons[service.iconName] ?? Zap;
  const intro = intros[service.slug] ?? service.description;
  const Icon = icon;
  return <main className="bg-[#fffdfa] pt-28 text-[#211b18] sm:pt-36">
    <section className="mx-auto max-w-[1120px] px-5 pb-20 lg:pb-28"><div className="mt-0 max-w-[860px]"><span className="grid size-12 place-items-center rounded-2xl border border-[#eadbd4] bg-white text-[#e84f1e] shadow-[0_4px_12px_rgba(61,37,24,.06)]"><Icon className="size-5" /></span><p className="mt-8 text-[11px] font-bold uppercase tracking-[.18em] text-[#c94a20]">{service.heroDetail}</p><h1 className="font-heading mt-4 text-[clamp(3.3rem,6.4vw,6.2rem)] font-medium leading-[.88] tracking-[-.075em]">{service.label}</h1><p className="font-heading mt-7 max-w-[680px] text-[clamp(1.55rem,2.4vw,2.05rem)] leading-[1.1] tracking-[-.045em] text-[#443832]">{service.tagline}</p><p className="mt-5 max-w-[630px] text-[17px] leading-[1.75] text-[#6e635d]">{intro}</p><Link href={`/work-with-us?service=${service.slug}`}><Button size="lg" className="mt-9">Discuss your project <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Button></Link></div></section>
    <section className="border-y border-[#eadfd9] bg-[#f9f5f2]"><div className="mx-auto grid max-w-[1120px] gap-12 px-5 py-20 lg:grid-cols-[.72fr_1.28fr] lg:py-28"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#c94a20]">What we help with</p><h2 className="font-heading mt-5 text-[clamp(2.4rem,4vw,4rem)] leading-[.94] tracking-[-.065em]">What's included in the process.</h2></div><div className="grid gap-0 border-t border-[#e5d9d2]">{service.features.map((feature, i) => { const FeatureIcon = icons[feature.iconName] ?? Zap; return <article key={feature.title} className="grid gap-4 border-b border-[#e5d9d2] py-7 sm:grid-cols-[52px_1fr] sm:gap-6"><span className="grid size-10 place-items-center rounded-xl border border-[#eadbd4] bg-white text-[#e84f1e]"><FeatureIcon className="size-[18px]" /></span><div><div className="flex items-baseline justify-between gap-4"><h3 className="font-heading text-[25px] tracking-[-.045em]">{feature.title}</h3><span className="text-[11px] font-bold tabular-nums text-[#b8a79f]">0{i + 1}</span></div><p className="mt-2 max-w-[580px] text-[14px] leading-[1.7] text-[#70645d]">{feature.description}</p></div></article>})}</div></div></section>
    <section className="mx-auto max-w-[1120px] px-5 py-20 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#c94a20]">What you receive</p><h2 className="font-heading mt-5 text-[clamp(2.4rem,4vw,4rem)] leading-[.94] tracking-[-.065em]">What you get at the end.</h2></div><div><p className="max-w-[590px] text-[17px] leading-[1.72] text-[#625750]">Everything documented and organized. Your team can reference the designs, reuse components, and understand the decisions we made.</p><div className="mt-9 grid gap-x-7 sm:grid-cols-2">{service.included.map(item => <div key={item} className="flex items-center gap-2.5 border-b border-[#eadfd9] py-3.5 text-[13px] font-medium text-[#4d433e]"><Check className="size-4 shrink-0 text-[#e84f1e]" />{item}</div>)}</div></div></div></section>
    <section className="border-y border-[#eadfd9] bg-[#211b18] text-white"><div className="mx-auto max-w-[1120px] px-5 py-20 lg:py-28"><div className="max-w-[670px]"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#ff9c78]">Investment</p><h2 className="font-heading mt-5 text-[clamp(2.4rem,4vw,4rem)] leading-[.94] tracking-[-.065em]">Choose your package.</h2><p className="mt-5 text-[16px] leading-[1.7] text-white/[.65]">Fixed prices to get started. If your project doesn't fit these tiers, we'll create a custom scope after our discovery call.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{service.pricing.map(tier => <article key={tier.name} className={`relative flex flex-col rounded-2xl border p-6 ${tier.highlighted ? "border-[#ff6b35] bg-[#ff6b35]" : "border-white/[.13] bg-white/[.05]"}`}>{tier.badge && <span className="absolute -top-3 left-6 rounded-full bg-white px-3 py-1 text-[10px] font-bold text-[#c94a20]">{tier.badge}</span>}<p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/[.55]">{tier.name}</p><p className="font-heading mt-4 text-[38px] tracking-[-.06em]">{tier.price}</p><p className="mt-3 min-h-16 text-[13px] leading-[1.65] text-white/[.72]">{tier.description}</p><ul className="mt-6 flex-1 space-y-2.5 border-t border-white/[.15] pt-6">{tier.features.map(item => <li key={item} className="flex gap-2 text-[12px] leading-[1.5] text-white/[.82]"><Check className="mt-0.5 size-3.5 shrink-0" />{item}</li>)}</ul><Link href={`/work-with-us?service=${service.slug}&plan=${tier.name.toLowerCase()}`} className={`mt-auto mt-8 inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-[13px] font-semibold transition-all hover:-translate-y-0.5 ${tier.highlighted ? "bg-white text-[#2b211c] shadow-md hover:bg-white/90" : "border border-white/[.24] text-white hover:bg-white/[.08]"}`}>Choose {tier.name}<ArrowUpRight className="size-4" /></Link></article>)}</div></div></section>
    <section className="mx-auto max-w-[860px] px-5 py-20 lg:py-28"><div className="text-center"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#c94a20]">Questions, answered</p><h2 className="font-heading mt-5 text-[clamp(2.4rem,4vw,4rem)] leading-[.94] tracking-[-.065em]">Common questions.</h2></div><Accordion type="single" collapsible className="mt-12 space-y-3">{service.faq.map((item, i) => <AccordionItem key={item.question} value={`faq-${i}`}><AccordionTrigger><span className="flex items-center gap-3"><HelpCircle className="size-4 shrink-0 text-[#ff6b35]" />{item.question}</span></AccordionTrigger><AccordionContent>{item.answer}</AccordionContent></AccordionItem>)}</Accordion></section>
    <section className="mx-auto max-w-[1120px] px-5 pb-20 lg:pb-28"><div className="rounded-[28px] bg-[#f2e7df] p-8 sm:p-12 lg:flex lg:items-end lg:justify-between lg:p-14"><div className="max-w-[600px]"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#c94a20]">Ready when you are</p><h2 className="font-heading mt-5 text-[clamp(2.4rem,4vw,4rem)] leading-[.94] tracking-[-.065em]">Ready to start your project.</h2></div><Link href={`/work-with-us?service=${service.slug}`} className="group mt-8 inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#211b18] px-5 py-3.5 text-[14px] font-semibold text-white transition-transform hover:-translate-y-0.5 lg:mt-0">Work with us <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></div></section>
  </main>;
}
